- name: Install Redis Repos
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install Redis
  yum:
    name: redis
    enablerepo: yes
    state: present

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis service
  systemd:
    name: redis
    enabled: yes
    state: restarted