- name: Sample Playbook1
  hosts: all
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello
    - name: Print World
      ansible.builtin.debug:
        msg: World

- name: Sample Play2
  hosts: all
  tasks:
    - name: Print Bye
      ansible.builtin.debug:
        msg: Bye
    - name: World
      ansible.builtin.debug:
        msg: World
        #
