- name: Install NodeJS
  yum:
    - nodejs
    - make
    - gcc-c++

- name: Create roboshop user
  user:
    name: roboshop

- name: Download Frontend Archive
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Remove old content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy Extracted Content to Nginx Path
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install NodeJS dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Setup Catalogue service file
  copy:
    src: systemd.service
    dest: /home/roboshop/catalogue/catalogue.service

- name: Start catalogue service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes
