- name: Update prometheus,records amd alerts file
  template:
    src: "{{item}}.yml"
    dest: /opt/prometheus/{{item}}.yml
  loop:
    - prometheus
    - records
    - alerts

- name: Restart Prometheus Service
  systemd:
    name: prometheus
    state: restarted
    enabled: yes