global:
  resolve_timeout: 30s
  slack_api_url : "https://hooks.slack.com/services/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"

route:
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#prom-alerts'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
