global:
  resolve_timeout: 1m
  slack_api_url : "https://hooks.slack.com/services/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"

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#prom-alerts'
    send_resolved: true

